spring:
  application:
    name: 2026-spring-team1
  datasource:
    url: jdbc:postgresql://localhost:5434/team1db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update      # 개발 초기엔 update. 운영선 validate/none 권장
    show-sql: true          # 실행되는 SQL을 콘솔에 보여줌 (개발 시 유용)
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081